version: 2
updates:
- package-ecosystem: npm
  open-pull-requests-limit: 10
  directory: "/"
  schedule:
    interval: monthly
  groups:
    dev-dependencies-js-yaml:
      patterns:
      - "@types/js-yaml"
      - "js-yaml"
    dev-dependencies-deep-extend:
      patterns:
      - "@types/deep-extend"
      - "deep-extend"
    dev-dependencies-rc:
      patterns:
      - "@types/rc"
      - "rc"
  reviewers:
  - fannheyward
